plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
branches:
  - "main"
repositoryUrl: https://github.com/diegotony/aws_cloudfront_distribution