name: Release Module

on:
  push:
    branches:
      - main


jobs:
  fmt:
    uses: diegotony/gh-pipelines/.github/workflows/terraform-fmt.yml@main
    secrets:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  release:
    needs: fmt
    uses: diegotony/gh-pipelines/.github/workflows/sm-release.yml@main
    secrets:
      token: ${{ secrets.GH_TOKEN }}
