name: Release Module

on:
  push:
    branches:
      - main


jobs:
  release:
    needs: fmt
    uses: diegotony/gh-pipelines/.github/workflows/sm-release.yml@main
    secrets:
      token: ${{ secrets.GH_TOKEN }}
