name: Release Module

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: diegotony/gh-pipelines/.github/workflows/semantic-release.yml@main
    secrets:
      token: ${{ secrets.GH_TOKEN }}
